apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  namespace: argocd   # ðŸ‘ˆ add this
  labels:
    app: pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: osagiefe/pyapplication:v2
          ports:
            - containerPort: 8080
