apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
spec:
  namespace: argocd   # ðŸ‘ˆ must match the namespace above
  type: LoadBalancer
  selector:
    app: pyapp
  ports:
    - port: 80
      targetPort: 8080
